# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Pod Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer

jobs:
  main:
    name: Pod Lint
    runs-on: macOS-13
    steps:
      - name: git checkout
        uses: actions/checkout@v5

      - name: pod lint
        run: pod lib lint --verbose
